apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-aks-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-aks-app"
  template:
    metadata:
      labels:
        app: "my-aks-app"
    spec:
      containers:
        - name: "my-aks-container"
          image: "your-container-image:latest"
          ports:
            - containerPort: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "my-aks-service"
spec:
  selector:
    app: "my-aks-app"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
